#!/bin/sh

mkdir -p opk
cp ./voxer.elf opk/
cp ./start.sh opk/
cp ./icon.png opk/icon.png
cp -r binary/Author opk/
cp -r binary/Highscores opk/
cp -r binary/Ingame opk/
cp -r binary/Menu opk/
cp -r binary/Music opk/
cp -r binary/System opk/

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

print '[Desktop Entry]
Type=Application
Name=Voxer
Comment=3D shmup
Exec=sh start.sh
Icon=icon
Terminal=false
Type=Application
Categories=games;
' > opk/default."$1".desktop

mksquashfs ./opk voxer_"$1".opk -all-root -noappend -no-exports -no-xattrs

rm -r opk
